name: envsml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - tqdm
  - opencv
  - pip
  - pip:
    - timm
    - gdown
    - tensorflow
