name: envsml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11 
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - tqdm
  - opencv 
  - pip 
  - tensorflow  
  - gdown  
  - zipfile  
  - collections 
  - matplotlib
  - random
  - pip:
      - timm
      - opencv-python
